### ISSUE TITLE
['a', 'b'].values() 是会出错么？

### ISSUE THREAD

**Issue by tomtsang** [ruanyf/es6tutorial#402]
['a', 'b'].values() 好像会报错。是我自己的问题么？

**Comment by tomtsang** [comment]
我的输出如下：
>  ['a', 'b'].values()
TypeError: ["a","b"].values is not a function
    at repl:1:12
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:545:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)

**Comment by ruanyf** [comment]
V8 还没实现。
