### ISSUE TITLE
第九章 第10节 对象的拓展运算符例子

### ISSUE THREAD

**Issue by pingsoli** [ruanyf/es6tutorial#436]
阮老师，你好。在运行
let z = { a: 3, b: 4 };
let n = { ...z };
n // { a: 3, b: 4 }
中，node直接出错，错误信息如下：
let n = { ...z };
          ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

我刚刚开始学习js，希望老师能够给出意见。

**Comment by ruanyf** [comment]
Chrome 还不支持这个语法。可以使用 Node 8.x。

**Comment by pingsoli** [comment]
我已经将node从6.11.0 LTS 变为现在的v8.1.2了，但是还是报错了。

**Comment by pingsoli** [comment]
@ruanyf  不好意思打扰了，我试过将我的node v6.11.0 LTS变为v8.1.2，但是node还是报同样的错误。这里我用的node是二进制非安装版，直接配置环境变量。希望您给出一点意见，谢谢。

**Comment by torrac12** [comment]
@pingsoli 
建议问这种问题之前可以自己先查一下
http://node.green/
http://kangax.github.io/compat-table/esnext/

**Comment by ruanyf** [comment]
不好意思，我记错了。Node 8.x 确实支持，但是默认没有打开这项功能。

你只有在 Babel 里面运行了。

**Comment by pingsoli** [comment]
@ruanyf tks，8.x版本是支持的，确实没有打开，可以直接通过--harmony选项来支持，也可以使用Babel。目前偷懒的做法，alias node='node --harmony'。谢谢阮老师。
