### ISSUE TITLE
对象的扩展_Object.md 第1314行例子运行 Uncaught SyntaxError: `...` must be followed by an identifier in declaration contexts

### ISSUE THREAD

**Issue by Tiancheng-Luo** [ruanyf/es6tutorial#630]
Object.md 第 1314行:  
下面是另一个例子。
```javascript
const o = Object.create({ x: 1, y: 2 });
o.z = 3;

let { x, ...{ y, z } } = o;
x // 1
y // undefined
z // 3
```
在chrome 63, 还是在Node 8.9.4中运行都会返回

Uncaught SyntaxError: `...` must be followed by an identifier in declaration contexts  
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at run ([eval]:971:15)
    at onRunRequest ([eval]:798:18)
    at onMessage ([eval]:758:13)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
